# This file lets GitHub users fund this project
# See https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

github: [NancieDev]
custom: ["https://www.drips.network/wave"]
